"""Every bundled template must render, with data and without it.

The failure this guards against is specific and expensive: a template that
works in a demo, where every field happens to be filled, and breaks on the
first real upload, where half the fields are empty because the photo was taken
at an angle. Partial extraction is the normal case, not the exception, so both
paths are tested for every template.

The templates are generated by scripts/build_templates.py. These tests assert
on the committed .docx files, so a hand-edit that breaks one is caught even if
nobody re-runs the generator.
"""

from __future__ import annotations

import io

import pytest
from docx import Document

from packages.docgen.engine import analyze, render_docx
from packages.schema.models import (
    Education,
    ExtractionResult,
    FieldValue,
    IdentityDocument,
    Subject,
)

TEMPLATE_DIR = __import__("pathlib").Path(
    __file__).resolve().parents[1] / "templates"

EXPECTED = [
    "ish_arizasi.docx",
    "malumotnoma.docx",
    "mehnat_shartnomasi.docx",
    "otm_arizasi.docx",
    "ishonchnoma.docx",
    "diplom_ilovasi.docx",
]

EXTRA = {
    "salary": 7500000,
    "position": "dasturchi",
    "employer": "«Namuna» MChJ",
    "university": "TATU",
    "attorney_number": "12/3",
}


def template_bytes(name: str) -> bytes:
    return (TEMPLATE_DIR / name).read_bytes()


def empty_result() -> ExtractionResult:
    r = ExtractionResult(job_id="empty")
    r.documents.append(IdentityDocument())
    r.education = Education()
    return r


def full_result() -> ExtractionResult:
    r = ExtractionResult(job_id="full")
    r.person.name.surname_latin = FieldValue(value="TOSHMATOV", confidence=1.0)
    r.person.name.given_name_latin = FieldValue(value="JASUR", confidence=1.0)
    r.person.name.patronymic_latin = FieldValue(value="BAXTIYOROVICH",
                                                confidence=1.0)
    r.person.name.surname_cyrillic = FieldValue(value="ТОШМАТОВ", confidence=1.0)
    r.person.name.given_name_cyrillic = FieldValue(value="ЖАСУР", confidence=1.0)
    r.person.birth_date = FieldValue(value="1993-06-12", confidence=1.0)
    r.person.birth_place = FieldValue(value="Samarqand viloyati", confidence=1.0)
    r.person.pinfl = FieldValue(value="31206930045612", confidence=1.0)
    r.person.address = FieldValue(value="Toshkent shahri", confidence=1.0)
    r.person.sex = FieldValue(value="M", confidence=1.0)
    r.person.citizenship = FieldValue(value="UZB", confidence=1.0)
    r.documents.append(IdentityDocument(
        doc_number=FieldValue(value="AC1928374", confidence=1.0),
        issuing_authority=FieldValue(value="IIB Chilonzor tumani", confidence=1.0),
        issue_date=FieldValue(value="2019-02-14", confidence=1.0),
    ))
    r.education = Education(
        institution=FieldValue(value="TATU", confidence=1.0),
        degree=FieldValue(value="bakalavr", confidence=1.0),
        speciality=FieldValue(value="Kompyuter injiniringi", confidence=1.0),
        speciality_code=FieldValue(value="60610100", confidence=1.0),
        diploma_number=FieldValue(value="1204/22", confidence=1.0),
        graduation_year=FieldValue(value="2022", confidence=1.0),
        gpa=FieldValue(value="4.1", confidence=1.0),
        subjects=[
            Subject(name=FieldValue(value="Oliy matematika", confidence=1.0),
                    hours=FieldValue(value="180", confidence=1.0),
                    credits=FieldValue(value="6", confidence=1.0),
                    grade=FieldValue(value="besh", confidence=1.0)),
            Subject(name=FieldValue(value="Fizika", confidence=1.0),
                    hours=FieldValue(value="120", confidence=1.0),
                    credits=FieldValue(value="4", confidence=1.0),
                    grade=FieldValue(value="yaxshi", confidence=1.0)),
        ],
    )
    return r


def all_text(docx_bytes: bytes) -> str:
    doc = Document(io.BytesIO(docx_bytes))
    parts = [p.text for p in doc.paragraphs]
    parts += [c.text for t in doc.tables for row in t.rows for c in row.cells]
    for section in doc.sections:
        parts += [p.text for p in section.header.paragraphs]
        parts += [p.text for p in section.footer.paragraphs]
    return "\n".join(parts)


@pytest.mark.parametrize("name", EXPECTED)
def test_template_file_exists(name: str) -> None:
    assert (TEMPLATE_DIR / name).exists(), (
        f"{name} is missing; run python scripts/build_templates.py"
    )


@pytest.mark.parametrize("name", EXPECTED)
def test_template_analyses_without_errors(name: str) -> None:
    _fixed, spec = analyze(template_bytes(name), name=name)
    assert not spec.errors, f"{name}: {spec.errors}"
    assert spec.variables, f"{name} declares no variables at all"


@pytest.mark.parametrize("name", EXPECTED)
def test_template_renders_with_full_data(name: str) -> None:
    result = render_docx(template_bytes(name), full_result(), extra=EXTRA)
    text = all_text(result.content)
    assert "{{" not in text and "{%" not in text, (
        f"{name} still contains unrendered tags"
    )


@pytest.mark.parametrize("name", EXPECTED)
def test_template_renders_with_no_data_at_all(name: str) -> None:
    """The realistic case. Missing fields become blanks, not exceptions."""
    result = render_docx(template_bytes(name), empty_result(), extra={})
    text = all_text(result.content)
    assert "{{" not in text and "{%" not in text
    assert "____" in text, f"{name} should show fill-in lines for empty fields"
    assert result.missing_fields, f"{name} did not report any missing field"


@pytest.mark.parametrize("name", EXPECTED)
def test_template_declares_no_unknown_variables(name: str) -> None:
    """Every field path must exist in the canonical schema.

    A typo here is silent at render time — the value simply never appears —
    which is exactly the "the template quietly does not work" failure the
    docgen design set out to eliminate.
    """
    _fixed, spec = analyze(template_bytes(name), name=name)
    assert not spec.unknown_variables, (
        f"{name} references paths that are not in the schema: "
        f"{spec.unknown_variables}"
    )


def test_subject_table_loop_repeats_one_row_per_subject() -> None:
    """The diploma supplement is the only template with a table loop."""
    result = render_docx(template_bytes("diplom_ilovasi.docx"), full_result(),
                         extra=EXTRA)
    doc = Document(io.BytesIO(result.content))
    subject_table = doc.tables[-1]
    rows = [[c.text for c in row.cells] for row in subject_table.rows]
    assert rows[0][0] == "Fan nomi"                    # header survives
    assert [r[0] for r in rows[1:]] == ["Oliy matematika", "Fizika"]
    assert rows[1][1:] == ["180", "6", "besh"]


def test_subject_table_is_empty_when_no_subjects_were_read() -> None:
    """An unreadable table must produce no rows, never invented ones."""
    result = render_docx(template_bytes("diplom_ilovasi.docx"), empty_result(),
                         extra={})
    doc = Document(io.BytesIO(result.content))
    subject_table = doc.tables[-1]
    assert len(subject_table.rows) == 1                # header only


def test_contract_conditional_follows_the_sex_field() -> None:
    """{% if %} branches must actually branch, in both directions."""
    male = full_result()
    female = full_result()
    female.person.sex = FieldValue(value="F", confidence=1.0)

    male_text = all_text(
        render_docx(template_bytes("mehnat_shartnomasi.docx"), male,
                    extra=EXTRA).content)
    female_text = all_text(
        render_docx(template_bytes("mehnat_shartnomasi.docx"), female,
                    extra=EXTRA).content)
    assert "mehnat ta'tiliga" in male_text
    assert "parvarish qilish" in female_text
    assert male_text != female_text


def test_amount_words_filter_reaches_the_contract() -> None:
    text = all_text(
        render_docx(template_bytes("mehnat_shartnomasi.docx"), full_result(),
                    extra={"salary": 7500000}).content)
    assert "million" in text.lower()


def test_apostrophes_are_normalised_on_the_way_out() -> None:
    """Uzbek Oʻ/Gʻ must leave the system as U+02BB, whatever came in."""
    r = full_result()
    r.person.name.surname_latin = FieldValue(value="G'OFUROV", confidence=1.0)
    text = all_text(
        render_docx(template_bytes("malumotnoma.docx"), r, extra=EXTRA).content)
    assert "GʻOFUROV" in text
